import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
    en: {
        appName: "Smart Industrial Monitor",
        kpiOverview: "KPI Overview", healthView: "Health View", energyView: "Energy View",
        alerts: "Alerts", userManagement: "User Management",
        logout: "Logout", collapse: "Collapse",
        maintenanceEngineer: "Maintenance Engineer", energyManager: "Energy Manager", itAdmin: "IT Admin",
        login: "Sign In", emailAddress: "Email address", password: "Password", signingIn: "Signing in…",
        emailVerificationTitle: "Verify Your Email",
        emailVerificationDesc: "A 6-digit code has been sent to",
        enterCode: "Enter verification code", verifyCode: "Verify",
        resendCode: "Resend code", verifying: "Verifying…",
        invalidCode: "Invalid or expired code. Please try again.",
        testAccounts: "Test Accounts", qrLoginTitle: "Login with QR Code",
        qrLoginDesc: "Scan with your mobile device", qrExpired: "QR expired — click to refresh",
        assetHealth: "Asset Health", avgHealthScore: "Avg Health Score",
        criticalAssets: "Critical Assets", cautionAssets: "Caution Assets", healthyAssets: "Healthy Assets",
        outOf100: "out of 100", assets: "assets",
        energyPerformance: "Energy Performance", pueTarget: "Target ≤ 1.5",
        eerNote: "Higher is better", co2Emissions: "Emissions",
        healthScore: "Health Score", rul: "RUL (days)", mtbf: "MTBF (hrs)",
        anomaly: "Anomaly", statusLabel: "Status", sensors: "Sensors",
        healthy: "Healthy", caution: "Caution", critical: "Critical",
        asset: "Asset", createWorkOrder: "Create Work Order",
        description: "Description", submit: "Submit", cancel: "Cancel", close: "Close",
        workOrderSuccess: "Work order created.", workOrderError: "Failed to create work order.",
        refresh: "Refresh", noAssets: "No assets found.",
        electricity: "Electricity", water: "Water", gas: "Gas", baseline: "Baseline",
        aboveBaseline: "Above baseline", electricity24h: "Electricity — 24h Actual vs Baseline",
        energyMetrics: "Energy Metrics — PUE / EER / CO₂", zone24hAvg: "24h zone averages",
        noMetricsData: "No energy metrics data available.",
        recordNewMetrics: "Record New Metrics", zone: "Zone", pue: "PUE", eer: "EER", co2KgH: "CO₂ (kg/h)",
        record: "Record", metricsRecorded: "Metrics recorded successfully.", metricsError: "Failed to record.",
        configureThresholds: "Configure Alert Thresholds",
        thresholdDesc: "Set the value at which an alert is triggered for an asset metric.",
        assetIdLabel: "Asset ID", metric: "Metric", threshold: "Threshold", save: "Save",
        thresholdSaved: "Threshold saved.", thresholdError: "Failed to save.",
        pueEfficiency: "PUE Efficiency", eerScore: "EER Score", co2VsTarget: "CO₂ vs Target",
        overTarget: "over target", underTarget: "under target", efficiency: "efficiency",
        overallPerformance: "Overall Energy Performance",
        activeAlerts: "Active Alerts", acknowledgedAlerts: "Acknowledged",
        acknowledge: "Acknowledge", acknowledged: "Acknowledged", noAlerts: "No active alerts.",
        userMgmtTitle: "User Management",
        userMgmtDesc: "Create, view, edit and delete user accounts.",
        addUser: "Add User", searchPlaceholder: "Search by name or email…",
        filterAllRoles: "All Roles", filterMaint: "Maintenance", filterEnergy: "Energy Mgr",
        filterAdmin: "IT Admin", filterActive: "Active", filterInactive: "Inactive",
        filterAllStatus: "All Status", name: "Name", email: "Email", role: "Role",
        statusCol: "Status", lastLogin: "Last Login", createdAt: "Created", actions: "Actions",
        edit: "Edit", delete: "Delete", confirmDelete: "Delete this user?",
        confirmDeleteSub: "This action cannot be undone.", noUsers: "No users found.",
        loadingUsers: "Loading users…", errorLoad: "Failed to load users.",
        modalAddTitle: "Add New User", modalEditTitle: "Edit User",
        fieldName: "Full Name", fieldEmail: "Email Address", fieldRole: "Role",
        fieldPassword: "Password", fieldPasswordEdit: "New Password (leave blank to keep current)",
        placeholderName: "e.g. Ahmed Ben Ali", placeholderEmail: "user@dashboard.com",
        placeholderPassword: "Min. 8 characters",
        roles: { maintenance_engineer: "Maintenance Engineer", energy_manager: "Energy Manager", it_admin: "IT Admin" },
        successAdd: "User created.", successEdit: "User updated.", successDelete: "User deleted.",
        successToggle: "Status updated.", successMarkInactive: "Inactive users marked.",
        activate: "Activate", deactivate: "Deactivate",
        activeStatus: "Active", inactiveStatus: "Inactive",
        total: "Total", usersLabel: "users", viewDetails: "View Details",
        detailTitle: "User Details", page: "Page", of: "of", prev: "Prev", next: "Next",
        lang: "FR", inactiveWarning: "Inactive 6+ months",
        markInactiveBtn: "Mark Inactive", markInactiveDesc: "Mark users inactive for 6+ months",
        cantDeleteAdmin: "Cannot delete IT Admin", cantDeleteSelf: "Cannot delete yourself",
        errorDelete: "Failed to delete user.", errorToggle: "Failed to update status.",
        hoursUntilDeletion: "h until deletion",
    },
    fr: {
        appName: "Moniteur Industriel Intelligent",
        kpiOverview: "Vue d'ensemble KPI", healthView: "Vue Santé", energyView: "Vue Énergie",
        alerts: "Alertes", userManagement: "Gestion des Utilisateurs",
        logout: "Déconnexion", collapse: "Réduire",
        maintenanceEngineer: "Ingénieur de Maintenance", energyManager: "Responsable Énergie", itAdmin: "Admin IT",
        login: "Se Connecter", emailAddress: "Adresse e-mail", password: "Mot de passe", signingIn: "Connexion…",
        emailVerificationTitle: "Vérifiez Votre E-mail",
        emailVerificationDesc: "Un code à 6 chiffres a été envoyé à",
        enterCode: "Entrez le code", verifyCode: "Vérifier",
        resendCode: "Renvoyer le code", verifying: "Vérification…",
        invalidCode: "Code invalide ou expiré. Veuillez réessayer.",
        testAccounts: "Comptes de Test", qrLoginTitle: "Connexion par QR Code",
        qrLoginDesc: "Scannez avec votre appareil mobile", qrExpired: "QR expiré — cliquez pour actualiser",
        assetHealth: "Santé des Équipements", avgHealthScore: "Score Santé Moyen",
        criticalAssets: "Équipements Critiques", cautionAssets: "En Alerte", healthyAssets: "Équipements Sains",
        outOf100: "sur 100", assets: "équipements",
        energyPerformance: "Performance Énergétique", pueTarget: "Cible ≤ 1,5",
        eerNote: "Plus c'est haut, mieux c'est", co2Emissions: "Émissions",
        healthScore: "Score Santé", rul: "DVR (jours)", mtbf: "MTBF (h)",
        anomaly: "Anomalie", statusLabel: "Statut", sensors: "Capteurs",
        healthy: "Sain", caution: "Attention", critical: "Critique",
        asset: "Équipement", createWorkOrder: "Créer un Ordre de Travail",
        description: "Description", submit: "Soumettre", cancel: "Annuler", close: "Fermer",
        workOrderSuccess: "Ordre de travail créé.", workOrderError: "Échec de la création.",
        refresh: "Actualiser", noAssets: "Aucun équipement trouvé.",
        electricity: "Électricité", water: "Eau", gas: "Gaz", baseline: "Référence",
        aboveBaseline: "Au-dessus de la référence", electricity24h: "Électricité — Réel vs Référence 24h",
        energyMetrics: "Métriques Énergétiques — PUE / EER / CO₂", zone24hAvg: "Moyennes zonales sur 24h",
        noMetricsData: "Aucune donnée de métriques énergétiques.",
        recordNewMetrics: "Enregistrer de Nouvelles Métriques", zone: "Zone", pue: "PUE", eer: "EER", co2KgH: "CO₂ (kg/h)",
        record: "Enregistrer", metricsRecorded: "Métriques enregistrées.", metricsError: "Échec.",
        configureThresholds: "Configurer les Seuils d'Alerte",
        thresholdDesc: "Définissez la valeur déclenchant une alerte pour une métrique.",
        assetIdLabel: "ID Équipement", metric: "Métrique", threshold: "Seuil", save: "Enregistrer",
        thresholdSaved: "Seuil enregistré.", thresholdError: "Échec.",
        pueEfficiency: "Efficacité PUE", eerScore: "Score EER", co2VsTarget: "CO₂ vs Cible",
        overTarget: "au-dessus de la cible", underTarget: "en dessous de la cible", efficiency: "efficacité",
        overallPerformance: "Performance Énergétique Globale",
        activeAlerts: "Alertes Actives", acknowledgedAlerts: "Acquittées",
        acknowledge: "Acquitter", acknowledged: "Acquitté", noAlerts: "Aucune alerte active.",
        userMgmtTitle: "Gestion des Utilisateurs",
        userMgmtDesc: "Créer, afficher, modifier et supprimer des comptes utilisateurs.",
        addUser: "Ajouter un Utilisateur", searchPlaceholder: "Recherche par nom ou e-mail…",
        filterAllRoles: "Tous les Rôles", filterMaint: "Maintenance", filterEnergy: "Énergie",
        filterAdmin: "Admin IT", filterActive: "Actif", filterInactive: "Inactif",
        filterAllStatus: "Tous les Statuts", name: "Nom", email: "E-mail", role: "Rôle",
        statusCol: "Statut", lastLogin: "Dernière Connexion", createdAt: "Créé le", actions: "Actions",
        edit: "Modifier", delete: "Supprimer", confirmDelete: "Supprimer cet utilisateur ?",
        confirmDeleteSub: "Cette action est irréversible.", noUsers: "Aucun utilisateur trouvé.",
        loadingUsers: "Chargement…", errorLoad: "Échec du chargement.",
        modalAddTitle: "Ajouter un Utilisateur", modalEditTitle: "Modifier l'Utilisateur",
        fieldName: "Nom Complet", fieldEmail: "Adresse E-mail", fieldRole: "Rôle",
        fieldPassword: "Mot de Passe", fieldPasswordEdit: "Nouveau Mot de Passe (laisser vide pour conserver)",
        placeholderName: "ex. Ahmed Ben Ali", placeholderEmail: "utilisateur@dashboard.com",
        placeholderPassword: "Min. 8 caractères",
        roles: { maintenance_engineer: "Ingénieur de Maintenance", energy_manager: "Responsable Énergie", it_admin: "Admin IT" },
        successAdd: "Utilisateur créé.", successEdit: "Utilisateur mis à jour.", successDelete: "Utilisateur supprimé.",
        successToggle: "Statut mis à jour.", successMarkInactive: "Utilisateurs inactifs marqués.",
        activate: "Activer", deactivate: "Désactiver",
        activeStatus: "Actif", inactiveStatus: "Inactif",
        total: "Total", usersLabel: "utilisateurs", viewDetails: "Voir les Détails",
        detailTitle: "Détails de l'Utilisateur", page: "Page", of: "sur", prev: "Préc.", next: "Suiv.",
        lang: "EN", inactiveWarning: "Inactif 6+ mois",
        markInactiveBtn: "Marquer Inactifs", markInactiveDesc: "Marquer les utilisateurs inactifs depuis 6+ mois",
        cantDeleteAdmin: "Impossible de supprimer un Admin IT", cantDeleteSelf: "Impossible de vous supprimer",
        errorDelete: "Échec de la suppression.", errorToggle: "Échec de la mise à jour.",
        hoursUntilDeletion: "h avant suppression",
    },
};

export function LanguageProvider({ children }) {
    const [language, setLang] = useState(() => localStorage.getItem("lang") || "en");
    function setLanguage(l) { setLang(l); localStorage.setItem("lang", l); }
    const t = (key) => translations[language]?.[key] ?? translations.en?.[key] ?? key;
    return (
        <LanguageContext.Provider value={{ t, language, setLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() { return useContext(LanguageContext); }
